### ISSUE TITLE
[CPP] Support Windows compilation

### ISSUE THREAD

**Issue by jt2594838** [apache/tsfile#100]
The TsFile-CPP can only be comiled on unix currently.
Compilation on Windows should be supported.

**Comment by HTHou** [comment]
Hi, Chris is working on it and I think it almost finished. 
https://github.com/apache/tsfile/pull/109

**Comment by hongzhi-gao** [comment]
Chris almost finished the job, so do we still need to support visual studio compilation?

**Comment by chrisdutz** [comment]
I had issues with the build not working with Visual Studio ... so I wen't back to MinGW ... but that's now finished. So don't expect any updates on that PR ;-) 

I think the next thing where we will need to work on, is having unit-tests being run by the maven build, but that's a new topic then.

**Comment by chrisdutz** [comment]
I enabled the Windows runners to also run the cpp ... ran into a tiny compilation problem on them ... fixed that ... now we should be ready to go.

**Comment by chrisdutz** [comment]
https://github.com/apache/tsfile/pull/109
