### ISSUE TITLE
[CPP] Add unit test

### ISSUE THREAD

**Issue by hongzhi-gao** [apache/tsfile#111]
Does the TsFile_CPP project require unit tests? Can we use third-party libraries such as Gtest or CppUnit ?

**Comment by chrisdutz** [comment]
So this is more a legal than a technical question .. from a quick check Gtest is BSD 3-Clause Licensed, which is ok .. CppUnit is GPL licensed, which is not ok.

We probably should remove the tooling for Unity integration as this seems to be a pure C test setup which we will most probably not be using.

**Comment by chrisdutz** [comment]
This looks as if integrating it into our build would be simple: 
https://google.github.io/googletest/quickstart-cmake.html

**Comment by 761417898** [comment]
Google Test requires C++11 since version 1.10.0 : 
https://github.com/google/googletest/blob/release-1.10.0/CMakeLists.txt 
So we might need to use an earlier version.

**Comment by jt2594838** [comment]
Good job. But I am afraid that we are facing something more challenging: verifying that TsFiles generated by the CPP edition can be read by the Java edition and vice versa. 

The motivation is that I just found the dictionary encoding implementation is different on both sides. Other similar issues would better be detected automatically.

Any idea about this?

**Comment by chrisdutz** [comment]
I guess an "integration-test" sub-module makes sense for this ... I would however think that this issue is about unit-testing the Cpp code itself, right?

**Comment by jt2594838** [comment]
Of course, we should open another issue for it.

**Comment by hongzhi-gao** [comment]
> This looks as if integrating it into our build would be simple: https://google.github.io/googletest/quickstart-cmake.html

The unit test framework chosen is GTest, as recommended by Chris.
The unit tests have been implemented for the `common`  `utils`  `file`  `encoding` section.  Here is the MR https://github.com/apache/tsfile/pull/134
