### ISSUE TITLE
[CPP] Inconsistent encoding implementation

### ISSUE THREAD

**Issue by jt2594838** [apache/tsfile#113]
I noticed that the DictionaryEncoder uses a BitPackingEncoder as the inner encoder in the CPP edition. However, in the Jave edition, the inner encoder is a RleEncoder (with bit-packing), which may cause incompatibility.

All encodings and compression in the CPP edition should be checked to ensure compatibility.

**Comment by hongzhi-gao** [comment]
I have done part of the related work.  https://github.com/apache/tsfile/pull/123

It seems that BitpackCodec corresponds to the IntRleCodec in the Java version, but BitpackCodec miscalculates the length of the `bit_width_` field during both encoding and decoding. This also causes DictionaryCodec to be inconsistent with the Java version.

BitpackCodec needs to properly handle 64-bit integers.

**Comment by hongzhi-gao** [comment]
Here is the ZigZagCodec related work  https://github.com/apache/tsfile/pull/124
The C++ Edition lacks explicit type casting in some unsigned right shift operations
Additionally, the header representing the encoded data should use `var_int` instead of `uint_8`.

**Comment by hongzhi-gao** [comment]
Here is the PlainCodec related work https://github.com/apache/tsfile/pull/125
I have completed all the unit tests for the codec and ensured that the intermediate results are consistent with the Java Edition. We may need more automated integration testing in the future. I will submit the unit test related code in the unit test issue later.

**Comment by 761417898** [comment]
> I have done part of the related work. #123
> 
> It seems that BitpackCodec corresponds to the IntRleCodec in the Java version, but BitpackCodec miscalculates the length of the `bit_width_` field during both encoding and decoding. This also causes DictionaryCodec to be inconsistent with the Java version.

BitpackCodec needs to properly handle 64-bit integers.
