### ISSUE TITLE
Concurrent access to a TsFile

### ISSUE THREAD

**Issue by cbiale** [apache/tsfile#218]
Is concurrent access to a TsFile possible using the API directly or should such accesses be handled using locks?

**Comment by jt2594838** [comment]
The answer is basically no. 
Concerning performance, we would like not to add concurrent control in TsFile, which does not seem quite meaningful in typical scenarios.
There is one exception: you may open several readers on the same CLOSED TsFile and perform concurrent queries.

**Comment by jt2594838** [comment]
Also, you may open several writers to write DIFFERENT TsFiles, but I guess it does not concern concurrent control.
For one thing, the TsFileConfig is a static object shared within a process. Any attempt to modify it during runtime should be aware of it.
